project/customers/models.py
from project import db,app

#create the customers table
class Customers(db.Model):
    customer_id = db.Column(db.Integer, primary_key = True)
    customer_name = db.Column(db.String(15), nullable= False)
    city = db.Column(db.String(15), nullable= False)
    age = db.Column (db.Integer, nullable= False)
    customer_image = db.Column(db.String(15), nullable= True)
    loan = db.relationship('Loans', backref='customers', lazy=True)


    # initialise 
    def __init__(self, customer_name, city, age, customer_image):
        self.customer_name = customer_name
        self.city = city
        self.age = age
        self.customer_image=customer_image

project/customers/__init__.py
"""an empty file 
    this file allows us to import components into main app.py file
    python needs this for it to understand that this is a module that it can import
    its also use for initializing the prog"""  

project/customers/views.py
import os
from flask import render_template, request, redirect, Blueprint
from project import db
from project.customers.models import Customers
from project.loans.models import Loans

"""
in this file we are defining the customers blue print setting & wrote all the end points that related to customers
"""

customers = Blueprint('customers', __name__, template_folder='templates')

#display customers:
@customers.route('/customers/', methods = ['GET'])
@customers.route('/customers/<id>')
def all_customers(id = -1):
    if int(id) == -1:
        return render_template('all_customers.html', customers = Customers.query.all())
    if int(id) > -1: 
        customer = Customers.query.get(int(id))
        return render_template('selected_customer.html', customer = customer)

#search customer
@customers.route('/search_customer', methods = ['POST'])
def search_customer():
    name = request.form['name']
    customer = Customers.query.filter(Customers.customer_name == name).first()
    if customer is None: 
        return redirect('/customers/')
    return redirect(f'/customers/{customer.customer_id}')

#add Customer 
@customers.route("/add_customer/", methods=['POST', 'GET'])
def add_customer():
    if request.method == "POST":
        customer_name = request.form.get("customer_name")
        city = request.form.get("city")
        age = request.form.get("age")
        customer_image = f'{request.form.get("customer_image")}.jpeg'

        customers_lst= os.listdir("project/static/customers")
        
        if customer_image not in customers_lst:
            customer_image = 'no_image.jpeg'

        newCustomer= Customers(customer_name, city, age, customer_image)
        db.session.add (newCustomer)
        db.session.commit()
        return render_template ('add_customer.html', customer_add=True)
    return render_template ('add_customer.html')

#delete customer
@customers.route("/delete_customer/<ind>", methods=['DELETE', 'GET'])
def del_customer(ind=-1):
        customer=Customers.query.get(int(ind))
        if customer:
            loans = Loans.query.filter_by(returned= False)
            for loan in loans:
                if loan.customer_id == customer.customer_id:
                    return render_template ('all_customers.html', customers = Customers.query.all(), active_loan=True)
            db.session.delete(customer)
            db.session.commit()
        return render_template('delete_customer.html', customer=customer)

project/customers/templates/add_customer.html
{% extends "layout.html" %}
{% block title %}add customer{% endblock %}
{% block head %}
{{ super() }}
{% endblock %}
{% block content %}

<div class="d-flex justify-content-center">
    <h2>add customer</h2>
</div>

<div class="d-flex justify-content-center">
    {% if customer_add == True %}
    <h5 style="color: red;"> customer add Successfully </h5>
    {% endif %}
</div>
<br>

<form action="{{ url_for('customers.add_customer') }}" method="POST">
    <label for="customer_name">customer name: </label>
    <input type="string" name="customer_name" id="customer_name" placeholder="customer_name" required> <br><br>
    <label for="city">city: </label>
    <input type="string" name="city" id="city" placeholder="city" required> <br><br>
    <label for="age">age: </label>
    <input type="number" name="age" id="age" placeholder="age" required min="0"> <br><br>
    <h6>Enter the customer name here <br> make sure to write in lowercase letters and separates the words with _ <br>
        (optional) </h6> <br>
    <label for="customer_image"> image: </label>
    <input type="string" name="customer_image" id="customer_image">

    <button type="submit">save</button> </form>
   
    {% endblock %}

project/customers/templates/all_customers.html
{% extends "layout.html" %}
{% block title %}all customers{% endblock %}
{% block head %}
{{ super() }}
{% endblock %}
{% block content %}


<div class="d-flex justify-content-center"><h2>customers</h2></div>

<div class="d-flex justify-content-center">
    {% if active_loan == True %}
    <h5 style="color: red;"> the customer has an active loan <br> you cant delete the customer before he will return the book</h5>
    {% endif %} <br>
    </div>
</div>

<a class="btn btn-success" href="/add_customer/">Add a customer</a> <br><br>

<form class="form-inline" action="/search_customer" method="post">
    <div class="input-group">
    <input type="text" class="from-control" name="name" placeholder="Search for a customer here."> 
        &nbsp; 
    <button class="btn btn-outline-success" type="submit">search book</button>
    </div>
</form> <br>

<div class="row row-cols-1 row-cols-md-4 g-4">
    {% for customer in customers %}
    <div class="col">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">{{customer.customer_name}} <style></style>
                </h5>
                <img src="/static/customers/{{customer.customer_image}}" class="card-img-top">
                <p class="card-text"> id: {{customer.customer_id}}</p>
                <p class="card-text">city: {{customer.city}} </p>
                <p class="card-text">age:{{customer.age }} </p>
                <a class="btn btn-danger" href="/delete_customer/{{customer.customer_id}}">delete this customer</a>
                <br><br>
            </div>
        </div>
    </div>



    {% endfor %}
</div>
{% endblock %}

project/customers/templates/delete_customer.html
{% extends "layout.html" %}
{% block title %}delete book{% endblock %}
{% block head %}
{{ super() }}
{% endblock %}
{% block content %}

<div class="d-flex justify-content-center"><h2>customer deleted  </h2></div> <br>
<div class="d-flex justify-content-center"><h4>{{customer.customer_name}} was removed from our library club subscription  </h4></div>
{% endblock %}

project/customers/templates/layout.html
<!doctype html>
<html>

<head>

  {% block head %}
  <link rel="shortcut icon" href="{{url_for('static', filename = 'favicon.ico')}}">
  <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
  <title>{% block title %}{% endblock %} - My Webpage</title>
  {% endblock %}

  <style>
    ul {
      list-style-type: none;
      margin: 0;
      padding: 0;
      overflow: hidden;
      background-color: rgb(36, 239, 225);
    }

    li {
      float: left;
    }

    li a {
      display: block;
      color: white;
      text-align: center;
      padding: 14px 16px;
      text-decoration: none;
    }

    li a:hover {
      background-color: #111;
    }

    #page-container {
      position: relative;
      min-height: 40vh;
    }

    #content-wrap {
      padding-bottom: 3.5rem;
    }

    #footer {
      background-color: white;
      position: fixed;
      left: 0;
      bottom: 0;
      width: 100%;
      height: 5%;
      text-align: center;
    }
  </style>

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
</head>

<body>
  <nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">shir's library</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/books">books</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/customers">customers</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/loans">loans</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <div id="content">{% block content %}{% endblock %}</div>
  <div id="page-container"></div>
  <div id="content-wrap"></div>

  <div id="footer">
    {% block footer %}
    &copy; All Rights Reserved to <a href="">shir epshtain</a> 2022
    {% endblock %}
  </div>

</body>

</html>

project/customers/templates/selected_customer.html
{% extends "layout.html" %}
{% block title %}customer{% endblock %}
{% block head %}
{{ super() }}
{% endblock %}
{% block content %}

<div class="d-flex justify-content-center"><h2>you looking for: </h2></div>
    <div class="row row-cols-1 row-cols-md-4 g-4">
    <div class="col">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">{{ customer.customer_name }} <style></style></h5>
            <img src="/static/customers/{{customer.customer_image}}" class="card-img-top">
                <p class="card-text"> id: {{customer.customer_id}}</p>
                <p class="card-text">city: {{customer.city}} </p>
                <p class="card-text">age:{{customer.age }} </p>
                <a class="btn btn-danger" href="/delete_customer/{{customer.customer_id}}">delete this customer</a> <br><br>
            </div>
        </div>
    </div>


{% endblock %}