project/books/models.py
from project import db,app

#create the books table
class Books(db.Model):
    book_id = db.Column(db.Integer, primary_key = True)
    book_name = db.Column(db.String(15), nullable= False)
    author = db.Column(db.String(15), nullable= False)
    year_published = db.Column (db.Integer, nullable= False)
    book_type = db.Column(db.String(15), nullable= False) 
    book_image = db.Column (db.String(15), nullable= True)
    loan= db.relationship('Loans', backref ='books', lazy=True)

    # initialise 
    def __init__(self, book_name, author, year_published, book_type, book_image):
        self.book_name = book_name
        self.author = author
        self.year_published = year_published
        self.book_type = book_type
        self.book_image = book_image


project/books/__init__.py
"""an empty file 
    this file allows us to import components into main app.py file
    python needs this for it to understand that this is a module that it can import
    its also use for initializing the prog"""  

project/books/views.py
import os
from flask import render_template, request, redirect, Blueprint
from project import db
from project.books.models import Books
from project.loans.models import Loans

"""
in this file we are defining the books blue print setting & wrote all the end points that related to books
"""
books = Blueprint('books', __name__, template_folder='templates', static_folder='static')

#display books:
@books.route('/books/', methods = ['GET'])
@books.route('/books/<id>')
def all_books(id = -1):
    if int(id) == -1:
        return render_template('all_books.html', books = Books.query.all())
    if int(id) > -1: 
        book = Books.query.get(int(id))
        return render_template('selected_book.html', book = book)

#search for a book
@books.route('/search_book', methods = ['POST'])
def search_book():
    
    name = request.form['name']
    print(name)
    book = Books.query.filter(Books.book_name == name).first()
    if book is None: 
        print(book)
        return redirect('/books/')
    return redirect(f'/books/{book.book_id}')

#add book 
@books.route("/add_book/", methods=['POST', 'GET'])
def add_book():
    if request.method == "POST":
        book_name = request.form.get("book_name")
        author = request.form.get("author")
        year_published = request.form.get("year_published")
        book_type = request.form.get("book_type")
        book_image = f'{request.form.get("book_image")}.jpeg'

        books_lst= os.listdir("project/static/books")
    
        if book_image not in books_lst:
            book_image = 'no_image.jpeg'

        newBook= Books(book_name, author, year_published, book_type, book_image)
        db.session.add (newBook)
        db.session.commit()
        return render_template('add_book.html', book_add=True)
    return render_template('add_book.html')

#delete book
@books.route("/delete_book/<ind>", methods=['DELETE', 'GET'])
def del_book(ind=-1):
        book=Books.query.get(int(ind))
        if book:
            loans = Loans.query.filter_by(returned= False)
            for loan in loans:
                if loan.book_id == book.book_id:
                    return render_template ('all_books.html', books = Books.query.all(), active_loan=True)
            db.session.delete(book)
            db.session.commit()
        return render_template('delete_book.html', book=book)

project/books/templates/add_book.html
{% extends "layout.html" %}
{% block title %}add book{% endblock %}
{% block head %}
{{ super() }}
{% endblock %}
{% block content %}

<div class="d-flex justify-content-center">
    <h2>add book</h2>
</div>

<div class="d-flex justify-content-center">
    {% if book_add == True %}
    <h5 style="color: red;"> book add Successfully </h5>
    {% endif %}
</div>
 <br>

<form action="{{ url_for('books.add_book') }}" method="POST">
    <label for="book_name">book name: </label>
    <input type="string" name="book_name" id="book_name" placeholder="book_name" required> <br><br>
    <label for="author">author: </label>
    <input type="string" name="author" id="author" placeholder="author" required> <br><br>
    <label for="year_published">year published: </label>
    <input type="string" name="year_published" id="year_published" placeholder="year_published" min="0" required>
    <br><br>
    <label for="book_type">book type: </label>
    <select name="book_type" id="book_type">book_type
        <option value="1 - loan time up to 10 days">1 - loan time up to 10 days</option>
        <option value="2 - loan time up to 5 days">2 - loan time up to 5 days</option>
        <option value="3 - loan time up to 2 days">3 - loan time up to 2 days</option>
    </select> <br><br>
    <h6>Enter the book name here <br> make sure to write in lowercase letters and separates the words with _ <br>
        (optional) </h6>
    <label for="book_image">image</label>
    <input type="string" name="book_image" id="book_image"> <br> <br>

    <button type="submit" >save</button>
</form>

{% endblock %}

project/books/templates/all_books.html
{% extends "layout.html" %}
{% block title %}all books{% endblock %}
{% block head %}
{{ super() }}
{% endblock %}
{% block content %}

<div class="d-flex justify-content-center">
    <h2>books</h2>
</div>
<a class="btn btn-success" href="/add_book/">Add a book</a> <br><br>

<form class="form-inline" action="/search_book" method="post">
    <div class="input-group">
        <input class="from-control" type="search" name="name" placeholder="Search for a book here."> &nbsp;
        <button class="btn btn-outline-success" type="submit">search book</button>
    </div>
</form> <br>

<div class="d-flex justify-content-center">
    {% if active_loan == True %}
    <h5 style="color: red;">this book is on loan <br> you cant delete this book right now!</h5>
    {% endif %} <br>
</div>

<div class="row row-cols-1 row-cols-md-4 g-4">
    {% for book in books %}
    <div class="col">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">{{book.book_name}} <style></style>
                </h5>
                <img src="/static/books/{{book.book_image}}" class="card-img-top">
                <p class="card-text">book id: {{book.book_id}}</p>
                <p class="card-text">author: {{book.author}} </p>
                <p class="card-text">year published: {{book.year_published}} </p>
                <p class="card-text">book type: {{book.book_type}} </p>
                <a class="btn btn-danger" href="/delete_book/{{book.book_id}}">delete this book</a> <br><br>
            </div>
        </div>
    </div>


    {% endfor %}
</div>
{% endblock %}

project/books/templates/delete_book.html
{% extends "layout.html" %}
{% block title %}all books{% endblock %}
{% block head %}
{{ super() }}
{% endblock %}
{% block content %}

<div class="d-flex justify-content-center"><h2>book deleted  </h2></div> <br>
<div class="d-flex justify-content-center"><h4>the book {{book.book_name}} was deleted from our library  </h4></div>
{% endblock %}

project/books/templates/layout.html
<!doctype html>
<html>

<head>

  {% block head %}
  <link rel="shortcut icon" href="{{url_for('static', filename = 'favicon.ico')}}">
  <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
  <title>{% block title %}{% endblock %} - My Webpage</title>
  {% endblock %}

  <style>
    ul {
      list-style-type: none;
      margin: 0;
      padding: 0;
      overflow: hidden;
      background-color: rgb(36, 239, 225);
    }

    li {
      float: left;
    }

    li a {
      display: block;
      color: white;
      text-align: center;
      padding: 14px 16px;
      text-decoration: none;
    }

    li a:hover {
      background-color: #111;
    }

    #page-container {
      position: relative;
      min-height: 40vh;
    }

    #content-wrap {
      padding-bottom: 3.5rem;
    }

    #footer {
      background-color: white;
      position: fixed;
      left: 0;
      bottom: 0;
      width: 100%;
      height: 5%;
      text-align: center;
    }
  </style>

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
</head>

<body>
  <nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">shir's library</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/books">books</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/customers">customers</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/loans">loans</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <div id="content">{% block content %}{% endblock %}</div>
  <div id="page-container"></div>
  <div id="content-wrap"></div>

  <div id="footer">
    {% block footer %}
    &copy; All Rights Reserved to <a href="">shir epshtain</a> 2022
    {% endblock %}
  </div>

</body>

</html>

project/books/templates/selected_book.html
{% extends "layout.html" %}
{% block title %}book{% endblock %}
{% block head %}
{{ super() }}
{% endblock %}
{% block content %}

<div class="d-flex justify-content-center"> <h2>you looking for: </h2></div>
    <div class="row row-cols-1 row-cols-md-4 g-4">
    <div class="col">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">{{book.book_name}} <style></style>
                </h5>
                <img src="/static/books/{{book.book_image}}" class="card-img-top">
                <p class="card-text">book id: {{book.book_id}}</p>
                <p class="card-text">author: {{book.author}} </p>
                <p class="card-text">year published: {{book.year_published}} </p>
                <p class="card-text">book type: {{book.book_type}} </p>
                <a class="btn btn-danger" href="/delete_book/{{book.book_id}}">delete this book</a> <br><br>
            </div>
        </div>
    </div>




{% endblock %}