project/loans/models.py
from project import db,app

#create the loans table
class Loans(db.Model):
    loan_id = db.Column (db.Integer, primary_key = True)
    customer_id = db.Column(db.Integer, db.ForeignKey('customers.customer_id'))
    book_id = db.Column(db.Integer, db.ForeignKey('books.book_id'))
    loan_date = db.Column(db.Date, nullable= False)
    return_date = db.Column(db.Date, nullable= True)
    returned=db.Column(db.Boolean, nullable= False)

    # initialise
    def __init__(self, customer_id, book_id, loan_date, return_date): 
        self.customer_id = customer_id
        self.book_id = book_id
        self.loan_date = loan_date
        self.return_date = return_date
        self.returned = False
    

project/loans/__init__.py
"""an empty file 
    this file allows us to import components into main app.py file
    python needs this for it to understand that this is a module that it can import
    its also use for initializing the prog"""  

project/loans/views.py
import datetime
import os
from flask import render_template, request, redirect, Blueprint
from project import db
from project.customers.models import Customers
from project.loans.models import Loans
from project.books.models import Books

"""
in this file we are defining the loans blue print setting & wrote all the end points that related to loans
"""

loans = Blueprint('loans', __name__, template_folder='templates')

#function to use at add loan
def max_loan(book, loan_date):
    delta_type1 = datetime.timedelta(days= 10)
    delta_type2 = datetime.timedelta(days=5)
    delta_type3 = datetime.timedelta(days= 2)

    if book.book_type == "1 - loan time up to 10 days": 
        return loan_date + delta_type1
    if book.book_type == "2 - loan time up to 5 days": 
        return loan_date + delta_type2
    if book.book_type == "3 - loan time up to 2 days": 
        return loan_date + delta_type3

def book_avilable(book_id, loans):
    for loan in loans:
        if loan.book_id == int(book_id):
            return False
    return True

#display loans
@loans.route("/loans/<book_id>")
@loans.route("/loans/", methods = ['GET'])
def display_all_or_part_loans(book_id= -1):
    # display one loan 
    for loan in Loans.query.all():
        if int(book_id) == loan.book_id:
            return render_template ("selected_loan.html", loan=loan)
    
    # display all loans
    return render_template ("all_loans.html", loans=Loans.query.all())

#loan a book (add loan) 
@loans.route("/add_loan/", methods=['POST', 'GET'])
def add_loan():
    if request.method == "POST":
        customer_id = request.form.get("customer_id")
        book_id = request.form.get("book_id")
        loan_date = datetime.datetime.strptime(request.form.get("loan_date"), "%Y-%m-%d")

        #some conditions in order to make correct loan:
        if not Customers.query.get(customer_id): 
            return render_template ("add_loan.html", customer=True )  
        if not Books.query.get(book_id): 
            return render_template ("add_loan.html", book=True )
        if not book_avilable(book_id, Loans.query.all()):
            return render_template ("add_loan.html", loan=True )

        book_t = Books.query.get(book_id)
        return_date = max_loan(book_t, loan_date)

        new_loan = Loans(customer_id, book_id, loan_date, return_date)
        db.session.add(new_loan)
        db.session.commit()

        return render_template ("add_loan.html" , loan_add=True) 
    return render_template ("add_loan.html") 


#return book (update the returned value) 
@loans.route("/return_book/<ind>", methods=['PUT', 'GET'])
def upd_returned(ind=-1):
    if int(ind) > -1:
        loan=Loans.query.get(int(ind))
        loan.returned = True
        db.session.commit()
    return render_template("return_book(loan).html", loan=loan)
            
#late loans
@loans.route("/late_loans/", methods=['GET']) 
def display_late_loans():
    late_loans = []
    late_time = []
    active_loans = Loans.query.filter_by(returned= False)
    for loan in active_loans:
        if loan.return_date < datetime.date.today():
            late_loans.append(loan)
            late_time.append((datetime.date.today()-loan.return_date).days)
    return render_template ("late_loans.html", late_loans=late_loans, late_time= late_time)

#delete loan
@loans.route("/delete_loan/<ind>", methods=['DELETE' , 'GET'])
def del_loan(ind=-1):
    loan=Loans.query.get(int(ind))
    if loan:
        if loan.returned == True:
            db.session.delete(loan)
            db.session.commit()
            return render_template ("delete_loan.html", loan=loan)
        else:
            return render_template ("all_loans.html", delme=True)

project/loans/templates/add_loan.html
{% extends "layout.html" %}
{% block title %}add loan{% endblock %}
{% block head %}
{{ super() }}
{% endblock %}
{% block content %}

<div class="d-flex justify-content-center">
    <h2>add loan</h2>
</div>

<div class="d-flex justify-content-center">
    {% if customer == True %}
    <h5 style="color: red;"> you cant add loan <br> customer is not exsist</h5>
    {% endif %} 

    {% if book == True %}
    <h5 style="color: red;">you cant add loan <br> book is not exsist</h5>
    {% endif %}

    {% if loan == True %}
    <h5 style="color: red;"> you cant add loan <br> book is already on loan</h5>
    {% endif %} 

    {% if loan_add == True %}
    <h5 style="color: red;"> loan add Successfully </h5>
    {% endif %} <br>
</div>

<form action="{{ url_for('loans.add_loan') }}" method="POST">
    <label for="customer_id">customer id: </label>
    <input type="number" name="customer_id" id="customer_id" placeholder="customer_id" min="0"> <br><br>
    <label for="book_id">book id: </label>
    <input type="number" name="book_id" id="book_id" placeholder="book_id" min="0"> <br><br>
    <label for="loan_date">loan date: </label>
    <input type="date" name="loan_date" id="loan_date" placeholder="loan_date">
    <button type="submit">save</button> </form>
    
    {% endblock %}

project/loans/templates/all_loans.html
{% extends "layout.html" %}
{% block title %}all loans{% endblock %}
{% block head %}
{{ super() }}
{% endblock %}
{% block content %}

<div class="d-flex justify-content-center">
    <h2>loans</h2>
</div>

<div class="d-flex justify-content-center">
    {% if delme == True %}
    <h5 style="color: red;"> you cant delete this loan <br> the book have to be returned first in order to delete</h5>
    {% endif %} 
</div>
    
<a class="btn btn-success" href="/add_loan/">add a loan</a> <br>
<a class="btn btn-danger" href="/late_loans/">display late loans</a> <br><br>

<div class="row row-cols-1 row-cols-md-4 g-4">
    {% for loan in loans %}
    <div class="col">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">loan id: {{loan.loan_id}}</h5>
                <p class="card-text">customer id: {{loan.customer_id}}</p>
                <p class="card-text">customer name: {% if loan.customer_id == None %} this customer was removed {% else %} {{loan.customers.customer_name}} {% endif %}</p>
                <p class="card-text">book id: {{loan.book_id}} </p>
                <p class="card-text">book name: {% if loan.book_id == None %} this book was removed {% else %} {{loan.books.book_name}} {% endif %}</p> 
                <p class="card-text">loan date: {{loan.loan_date}} </p>
                <p class="card-text">return date: {{loan.return_date}} </p>
                <p class="card-text">returned? {{loan.returned}} </p>
                <a class="btn btn-success" href="/return_book/{{loan.loan_id}}">return this book</a> <br>
                <a class="btn btn-danger" href="/delete_loan/{{loan.loan_id}}">delete this loan</a> <br><br>
            </div>
        </div>
    </div>


    {% endfor %}
</div>
{% endblock %}

project/loans/templates/delete_loan.html
{% extends "layout.html" %}
{% block title %}delete loan{% endblock %}
{% block head %}
{{ super() }}
{% endblock %}
{% block content %}

<div class="d-flex justify-content-center"><h2>loan deleted </h2></div> <br>
<div class="d-flex justify-content-center"><h4>book number {{loan.book_id}} just comeback to our library, go catch him  </h4></div>
{% endblock %}

project/loans/templates/late_loans.html
{% extends "layout.html" %}
{% block title %}Home Page{% endblock %}
{% block head %}
{{ super() }}

{% endblock %}
{% block content %}
<div class="d-flex justify-content-center"><h2>late loans</h2></div>
<div class="row row-cols-1 row-cols-md-4 g-4">
    {% for loan in late_loans %}
    <div class="col">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">late by {{late_time[late_loans.index(loan)]}} days</h5>
                <p class="card-text">loan id: {{loan.loan_id}}</p>
                <p class="card-text">customer id: {{loan.customer_id}}</p>
                <p class="card-text">book id: {{loan.book_id}} </p>
                <p class="card-text">loan date: {{loan.loan_date}} </p>
                <p class="card-text">return date: {{loan.return_date}} </p>
                <p class="card-text">returned? {{loan.returned}} </p>
            </div>
        </div>
    </div>



{% endfor %}
</div>
{% endblock %}

project/loans/templates/layout.html
<!doctype html>
<html>

<head>

  {% block head %}
  <link rel="shortcut icon" href="{{url_for('static', filename = 'favicon.ico')}}">
  <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
  <title>{% block title %}{% endblock %} - My Webpage</title>
  {% endblock %}

  <style>
    ul {
      list-style-type: none;
      margin: 0;
      padding: 0;
      overflow: hidden;
      background-color: rgb(36, 239, 225);
    }

    li {
      float: left;
    }

    li a {
      display: block;
      color: white;
      text-align: center;
      padding: 14px 16px;
      text-decoration: none;
    }

    li a:hover {
      background-color: #111;
    }

    #page-container {
      position: relative;
      min-height: 40vh;
    }

    #content-wrap {
      padding-bottom: 3.5rem;
    }

    #footer {
      background-color: white;
      position: fixed;
      left: 0;
      bottom: 0;
      width: 100%;
      height: 5%;
      text-align: center;
    }
  </style>

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
</head>

<body>
  <nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">shir's library</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/books">books</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/customers">customers</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/loans">loans</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <div id="content">{% block content %}{% endblock %}</div>
  <div id="page-container"></div>
  <div id="content-wrap"></div>

  <div id="footer">
    {% block footer %}
    &copy; All Rights Reserved to <a href="">shir epshtain</a> 2022
    {% endblock %}
  </div>

</body>

</html>

project/loans/templates/return_book(loan).html
{% extends "layout.html" %}
{% block title %}return book{% endblock %}
{% block head %}
{{ super() }}
{% endblock %}
{% block content %}

<div class="d-flex justify-content-center"><h2>book returned</h2></div> <br>
<div class="d-flex justify-content-center"><h4>thank you for return the book. </h4></div>

{% endblock %}

project/loans/templates/selected_loan.html
{% extends "layout.html" %}
{% block title %}all loans{% endblock %}
{% block head %}
{{ super() }}
{% endblock %}
{% block content %}

<div class="d-flex justify-content-center"><h2>you looking for: </h2></div>
    <div class="row row-cols-1 row-cols-md-4 g-4">
    <div class="col">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">loan id: {{loan.loan_id}}</h5>
                <p class="card-text">customer id: {{loan.customer_id}}</p>
                <p class="card-text">book id: {{loan.book_id}} </p>
                <p class="card-text">loan date: {{loan.loan_date}} </p>
                <p class="card-text">maximum return date: {{loan.maximum_return_date}} </p>
                <p class="card-text">returned? {{loan.returned}} </p>
            </div>
        </div>
    </div>

<a class="btn btn-danger" href="/delete_loan/{{loan.loan_id}}">delete this loan</a> <br><br>
{% endblock %}